language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  irc:
    channels:
    - "irc.stealth.net#esat"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
    template:
    - '#%{build_number} %{message} (%{branch} : %{author}): %{commit_message}'
after_success:
  - mvn clean cobertura:cobertura coveralls:report
